[git-filter-repo-py]
git-tree-sha1 = "a89e4e93a646719832599cecbda9ff9a0d319d9c"
lazy = false

    [[git-filter-repo-py.download]]
    url = "https://github.com/newren/git-filter-repo/archive/refs/tags/v2.34.0.tar.gz"
    sha256 = "2d89932fdaed0d6263dbf6aab3dcebbb5084f8787c42adee424081637feffe0e"
